export const DevList = [
    {
        id:1,
        url:"https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
        title:"FullStack Developer",
        item1:"Strong CS foundation",
        item2:"Project Experience",
        item3:"Worked with different frameworks",
    },
    {
        id:2,
        url:"https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
        title:"FullStack Developer",
        item1:"Strong CS foundation",
        item2:"Project Experience",
        item3:"Worked with different frameworks",
    },
    {
        id:3,
        url:"https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
        title:"FullStack Developer",
        item1:"Strong CS foundation",
        item2:"Project Experience",
        item3:"Worked with different frameworks",
    },
    {
        id:4,
        url:"https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
        title:"FullStack Developer",
        item1:"Strong CS foundation",
        item2:"Project Experience",
        item3:"Worked with different frameworks",
    },
    {
        id:5,
        url:"https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
        title:"FullStack Developer",
        item1:"Strong CS foundation",
        item2:"Project Experience",
        item3:"Worked with different frameworks",
    },
    {
        id:6,
        url:"https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
        title:"FullStack Developer",
        item1:"Strong CS foundation",
        item2:"Project Experience",
        item3:"Worked with different frameworks",
    },
]