export const DevList = [
  {
    id: 1,
    url: "https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
    title: "Mern Stack Developer",
    item1: "Strong CS foundation",
    item2: "Frontend with React",
    item3: "Backend with Node JS,Express JS & MongoDB",
  },
  {
    id: 2,
    url: "https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
    title: "Mean Stack Developer",
    item1: "Strong CS foundation",
    item2: "Frontend with React",
    item3: "Backend with Node JS,Express JS & MongoDB",
  },
  {
    id: 3,
    url: "https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
    title: ".NET & Angular Stack",
    item1: "Strong CS foundation",
    item2: "Fronted with Angular",
    item3: "Backend with Node JS,Express JS & MongoDB",
  },
  {
    id: 4,
    url: "https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
    title: "Java FullStack Developer",
    item1: "Strong CS foundation",
    item2: "Fronted with Angular/React",
    item3: "Backend with Java Spring Boot",
  },
  {
    id: 5,
    url: "https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
    title: " Python FullStack Developer",
    item1: "Strong CS foundation",
    item2: "Fronted with React/Vue",
    item3: "Backend with Python Django/Flask/FastAPI",
  },
  {
    id: 6,
    url: "https://miro.medium.com/max/1000/1*1n5PmMFrZKSj05PmqEE9yQ.png",
    title: "See other types of Developers",
    item1: "Strong CS foundation",
    item2: "Project Experience",
    item3: "Worked with different frameworks",
  },
];
